# Generated by Django 5.1.7 on 2025-03-22 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_alter_ocorrencia_acoes_tomadas'),
        ('planos_acao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planoacao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='planoacao',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='planoacao',
            name='ocorrencia_relacionada',
        ),
        migrations.RemoveField(
            model_name='planoacao',
            name='titulo',
        ),
        migrations.AddField(
            model_name='planoacao',
            name='ocorrencia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='planos_acao', to='ocorrencias.ocorrencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='prazo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='responsavel',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], max_length=20),
        ),
    ]
