# Generated by Django 5.1.7 on 2025-03-22 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0004_alter_ocorrencia_acoes_tomadas'),
        ('planos_acao', '0002_remove_planoacao_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoacao',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocorrencias.ocorrencia'),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], max_length=20),
        ),
    ]
