# Generated by Django 5.1.7 on 2025-03-22 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planos_acao', '0003_alter_planoacao_ocorrencia_alter_planoacao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planoacao',
            name='responsavel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='planoacao',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], max_length=50),
        ),
    ]
