# Generated by Django 4.2.19 on 2025-03-12 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_destinatarios', models.TextField(help_text='E-mails separados por vírgula')),
                ('horario_envio', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoAutomacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emails_destinatarios', models.TextField(blank=True, null=True)),
                ('assunto', models.CharField(default='Sinopse Diária - ', max_length=255)),
                ('mensagem', models.TextField(default='Segue, anexo, sinopse diária.')),
                ('horario_envio', models.TimeField(help_text='Horário do envio diário')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSinopse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=255)),
                ('detalhes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ocorrencia', models.DateField()),
                ('horario', models.TimeField()),
                ('nome_local', models.CharField(max_length=100)),
                ('relato', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ocorrencias/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído')], default='pendente', max_length=15)),
                ('responsavel', models.CharField(max_length=100)),
                ('envolvidos', models.TextField(blank=True, null=True)),
                ('acoes_tomadas', models.TextField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.local')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ocorrencias.tipoocorrencia')),
            ],
        ),
    ]
