# Generated by Django 4.2.19 on 2025-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='horario',
            field=models.TimeField(verbose_name='Horário'),
        ),
    ]
