# Generated by Django 5.1.7 on 2025-03-17 01:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0002_alter_ocorrencia_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ocorrencias'),
        ),
    ]
