# Generated by Django 5.1.7 on 2025-03-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocorrencias', '0003_alter_ocorrencia_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='acoes_tomadas',
            field=models.TextField(blank=True, null=True, verbose_name='Ações Tomadas'),
        ),
    ]
