# Generated by Django 4.2.19 on 2025-03-13 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número da Chave')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('cor_chaveiro', models.CharField(max_length=50, verbose_name='Cor do Chaveiro')),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField(auto_now_add=True, verbose_name='Data de Saída')),
                ('horario_saida', models.TimeField(auto_now_add=True, verbose_name='Horário de Saída')),
                ('responsavel', models.CharField(max_length=255, verbose_name='Nome do Responsável')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone do Responsável')),
                ('status', models.CharField(choices=[('Devolvida', 'Devolvida'), ('Não Devolvida', 'Não Devolvida')], default='Não Devolvida', max_length=15, verbose_name='Status')),
                ('operador_saida', models.CharField(max_length=255, verbose_name='Operador de Saída')),
                ('data_devolucao', models.DateField(blank=True, null=True, verbose_name='Data de Devolução')),
                ('horario_devolucao', models.TimeField(blank=True, null=True, verbose_name='Horário de Devolução')),
                ('operador_devolucao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Operador de Devolução')),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_chaves.chave', verbose_name='Chave')),
            ],
        ),
    ]
