# Generated by Django 4.2.19 on 2025-03-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='descricao',
        ),
        migrations.AddField(
            model_name='chave',
            name='nome',
            field=models.CharField(default='Chave Padrão', max_length=100, verbose_name='Nome da Chave'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chave',
            name='numero',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número da Chave'),
        ),
    ]
