# Generated by Django 4.2.19 on 2025-03-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0002_remove_chave_descricao_chave_nome_alter_chave_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='disponivel',
            field=models.BooleanField(default=True, verbose_name='Disponível'),
        ),
        migrations.AddField(
            model_name='movimentacaochave',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='nome',
            field=models.CharField(default='Chave Desconhecida', max_length=255, verbose_name='Nome da Chave'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número da Chave'),
        ),
        migrations.AlterField(
            model_name='movimentacaochave',
            name='data_saida',
            field=models.DateField(verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='movimentacaochave',
            name='horario_saida',
            field=models.TimeField(verbose_name='Horário de Saída'),
        ),
    ]
