# Generated by Django 4.2.19 on 2025-03-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0003_chave_disponivel_movimentacaochave_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaochave',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail do Responsável'),
        ),
    ]
