# Generated by Django 4.2.19 on 2025-03-14 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0004_movimentacaochave_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciclagemVigilante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_colaborador', models.CharField(max_length=255, verbose_name='Nome do Colaborador')),
                ('data_ultima_reciclagem', models.DateField(verbose_name='Data da Última Reciclagem')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status', models.CharField(blank=True, choices=[('No Prazo', 'No Prazo'), ('Programar Reciclagem', 'Programar Reciclagem'), ('Vencido', 'Vencido')], max_length=20, verbose_name='Status')),
                ('dias_para_vencimento', models.IntegerField(blank=True, null=True, verbose_name='Dias para Vencimento')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='diplomas/', verbose_name='Diploma de Reciclagem')),
            ],
        ),
    ]
