# Generated by Django 4.2.19 on 2025-03-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0005_reciclagemvigilante'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFundamental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_documento', models.CharField(max_length=255, verbose_name='Nome do Documento')),
                ('emissao', models.DateField(verbose_name='Data de Emissão')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('entidade_emissora', models.CharField(max_length=255, verbose_name='Entidade Emissora')),
                ('funcao_documento', models.CharField(max_length=255, verbose_name='Função do Documento')),
                ('validade', models.IntegerField(verbose_name='Validade (em dias)')),
                ('status', models.CharField(blank=True, choices=[('No Prazo', 'No Prazo'), ('Vence em Breve', 'Vence em Breve'), ('Vencido', 'Vencido')], max_length=15, verbose_name='Status')),
                ('area', models.CharField(choices=[('Segurança', 'Segurança'), ('Administrativo', 'Administrativo'), ('Operacional', 'Operacional'), ('Outro', 'Outro')], max_length=50, verbose_name='Área')),
            ],
        ),
    ]
