# Generated by Django 4.2.19 on 2025-03-15 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0007_atendimentoambulatorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofundamental',
            name='arquivo',
            field=models.FileField(default=' ', upload_to='documentos/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentofundamental',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
    ]
