# Generated by Django 4.2.19 on 2025-03-15 23:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0008_documentofundamental_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofundamental',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='documento'),
        ),
    ]
