# Generated by Django 4.2.19 on 2025-03-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0009_alter_documentofundamental_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofundamental',
            name='status',
            field=models.CharField(blank=True, choices=[('No Prazo', 'No Prazo'), ('Renovar', 'Renovar'), ('Vencido', 'Vencido')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='documentofundamental',
            name='validade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Validade (em dias)'),
        ),
    ]
