# Generated by Django 4.2.19 on 2025-03-16 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0010_alter_documentofundamental_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentofundamental',
            name='validade',
        ),
    ]
