# Generated by Django 5.1.7 on 2025-03-19 22:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0011_remove_documentofundamental_validade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reciclagemvigilante',
            name='diploma',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Diploma de Reciclagem', max_length=255, null=True, verbose_name='diplomas'),
        ),
    ]
