# Generated by Django 5.1.7 on 2025-03-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0012_alter_reciclagemvigilante_diploma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área')),
                ('tipo', models.CharField(choices=[('Vigilante', 'Vigilante'), ('Funcionário', 'Funcionário'), ('Prestador', 'Prestador de Serviço'), ('Lojista', 'Lojista'), ('Administração', 'Administração'), ('Comercial', 'Comercial'), ('Segurança', 'Segurança'), ('Estacionamento', 'Estacionamento'), ('Manutenção', 'Manutenção')], default='Funcionário', max_length=50, verbose_name='Tipo de Usuário')),
            ],
        ),
    ]
