# Generated by Django 5.1.7 on 2025-03-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0013_colaborador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacaochave',
            name='email',
        ),
        migrations.RemoveField(
            model_name='movimentacaochave',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='movimentacaochave',
            name='data_saida',
            field=models.DateField(auto_now_add=True, verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='movimentacaochave',
            name='horario_saida',
            field=models.TimeField(auto_now_add=True, verbose_name='Horário de Saída'),
        ),
        migrations.AlterField(
            model_name='movimentacaochave',
            name='responsavel',
            field=models.CharField(max_length=255, verbose_name='Responsável'),
        ),
    ]
