# Generated by Django 5.1.7 on 2025-03-20 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0014_remove_movimentacaochave_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='area',
            field=models.CharField(default=' ', max_length=100, verbose_name='Área'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(default='', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='tipo',
            field=models.CharField(choices=[('Vigilante', 'Vigilante'), ('Funcionário', 'Funcionário'), ('Prestador', 'Prestador de Serviço'), ('Lojista', 'Lojista'), ('Administração', 'Administração'), ('Comercial', 'Comercial'), ('Segurança', 'Segurança'), ('Estacionamento', 'Estacionamento'), ('Manutenção', 'Manutenção')], max_length=20, verbose_name='Tipo de Usuário'),
        ),
    ]
