# Generated by Django 5.1.7 on 2025-03-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0015_alter_colaborador_area_alter_colaborador_telefone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='area',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(default='', max_length=100, verbose_name='Função'),
            preserve_default=False,
        ),
    ]
