# Generated by Django 5.1.7 on 2025-03-20 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0016_remove_colaborador_area_colaborador_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacaochave',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='movimentacaochave',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='movimentacaochave',
            name='data_saida',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='movimentacaochave',
            name='horario_saida',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Horário de Saída'),
        ),
    ]
