# Generated by Django 4.2.19 on 2025-03-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loja', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='notificacoes/')),
                ('data_ocorrencia', models.DateTimeField()),
                ('itens_notificados', models.TextField(default='Nenhum item registrado')),
                ('notificado_por', models.CharField(default='Desconhecido', max_length=100)),
            ],
        ),
    ]
