# Generated by Django 4.2.19 on 2025-03-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_ocorrencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='itens_notificados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='notificado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table='notificacoes_notificacao',
        ),
    ]
