# Generated by Django 4.2.19 on 2025-03-12 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_alter_notificacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificacao',
            options={},
        ),
        migrations.AddField(
            model_name='notificacao',
            name='hora_ocorrencia',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='data_ocorrencia',
            field=models.DateField(default=datetime.datetime(2025, 3, 12, 1, 39, 29, 890792, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='notificacao',
            table=None,
        ),
    ]
