# Generated by Django 4.2.19 on 2025-03-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_alter_notificacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='data_ocorrencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
