# Generated by Django 4.2.19 on 2025-03-14 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_alter_notificacao_data_ocorrencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacao',
            name='itens_notificados',
        ),
    ]
