# Generated by Django 4.2.19 on 2025-03-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_remove_notificacao_itens_notificados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='loja',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='notificado_por',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
