# Generated by Django 4.2.19 on 2025-03-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0006_alter_notificacao_loja_alter_notificacao_motivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='hora_ocorrencia',
            field=models.TimeField(verbose_name='Horário'),
        ),
    ]
