# Generated by Django 5.1.7 on 2025-03-17 01:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0007_alter_notificacao_hora_ocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='notificacoes'),
        ),
    ]
